### ISSUE TITLE
getStatus not working

### ISSUE THREAD

**Issue by botcheddevil** [atom/git-utils#32]
returns empty object

    $ node
    > git = require('git-utils');
    { open: [Function] }
    > repo =  git.open('/Users/me/public_html/repo');
    { caseInsensitiveFs: true, submodules: {} }
    > repo.getStatus();
    {}

git-utils@1.4.1 and node@0.11.10:

**Comment by kevinsawicki** [comment]
Closing this out since it wasn't reproducible and hasn't been confirmed by others, please comment if you are still experiencing it.
