### ISSUE TITLE
Incompatible native module

### ISSUE THREAD

**Issue by prrrnd** [atom/git-utils#40]
A package I created requires git-utils, however it doesn't seem to be compatible in atom 0.190.0 (Chrome 41.0.2272.76 and Node 1.5.1)

```
Git Projects 1.13.0
Listed below are the incompatible native modules that this package depends on.

git-utils@3.0.0
Error message: Module version mismatch. Expected 43, got 14.
```
It seems like git-utils is not compatible with Node 1.5.1.

**Comment by maxbrunsfeld** [comment]
It looks like `git-utils` was installed with `npm install`. This compiles it to work with node.js, but not Atom. You should just need to run `apm rebuild` from your package directory. Let me know if this does not work for you!
