### ISSUE TITLE
Git worktrees not supported

### ISSUE THREAD

**Issue by karrots** [atom/git-utils#64]
It seems that Git work trees are not recognized by git-utils. Is this just a Git version issue or another problem?

https://git-scm.com/docs/git-worktree

https://github.com/subesokun/atom-tree-view-git-status/issues/19

**Comment by joshaber** [comment]
We use libgit2, which unfortunately doesn't yet support worktrees. The implementation is in progress: https://github.com/libgit2/libgit2/pull/3436

**Comment by karrots** [comment]
ok thanks for the update.

**Comment by allblackt** [comment]
+1 on this issue and thanks for the update!

**Comment by alvinhochun** [comment]
Just an update here that libgit2 has implemented worktree support so this issue should no longer be blocked. Would someone please remove the blocked label?

**Comment by Arcanemagus** [comment]
Looks like this was fixed in #77.
