### ISSUE TITLE
Incorrect isIgnored with negation

### ISSUE THREAD

**Issue by tgandrews** [atom/git-utils#73]
In Atom, files are ignored if git ignores them. This does not work if you have complicated negation rules. This is due to an issue in libgit2. This will be resolved by https://github.com/libgit2/libgit2/pull/3895

This issue is to track the issue above so that when it is merged git-utils can be updated to a later version libgit2.

**Comment by 50Wliu** [comment]
So the above PR has been merged.  Now we're just waiting on a libgit2 release and then someone with knowledge of git-utils will have to update the dependency.

**Comment by 50Wliu** [comment]
Fixed by #71.
