### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by jsolisu** [atom/git-utils#75]
Cannot install 4.1.3 version using npm install git-utils. With version 4.1.2 works.

**c1 : fatal error C1083: Cannot open source file: '..\deps\libgit2\src\win32\pthread.c': No such file or directory [E:\TEMP\node_modules\git-utils\build\libgit2.vcxproj]**

Thanks.

**Comment by damieng** [comment]
Sorry about that, caught out by a file rename in libgit2 dependency.  4.1.4 should now be out and working.
