### ISSUE TITLE
Install error: /bin/sh: 1: node: not found

### ISSUE THREAD

**Issue by kurdtpage** [atom/git-utils#82]
I have installed npm version 3.5.2 (fresh install), installing git-utils.

Screenshot:
![screenshot_2017-11-30_08-30-20](https://user-images.githubusercontent.com/1308716/33394919-c408cf24-d5a8-11e7-9754-c48ddb2819b5.png)

Log file:
[npm-debug.log](https://github.com/atom/git-utils/files/1515232/npm-debug.log)

**Comment by 50Wliu** [comment]
Make sure you have [node](https://nodejs.org) installed and try again.

**Comment by kurdtpage** [comment]
Node is obviously a pre-requisite to installing git-utils, so maybe there needs to be a check done to ensure it is installed first and a helpful exit message if it's not found?
