### ISSUE TITLE
.getHead and .getHeadAsync have different behaviors when called on new repo

### ISSUE THREAD

**Issue by leroix** [atom/git-utils#83]
On a newly created repo without any commits, `.getHead()` returns `null` while `.getHeadAsync()` results in an exception `Error: Git head failed`. I think they should be consistent with each other, but I'm not sure what the ideal would be. I'm leaning towards returning/resolving `null`.

/cc @BinaryMuse @maxbrunsfeld 

related https://github.com/atom/atom/issues/15920

**Comment by maxbrunsfeld** [comment]
> I'm leaning towards returning/resolving null.

:+1:
