### ISSUE TITLE
Status Code Number Means?

### ISSUE THREAD

**Issue by vnpnlz** [atom/git-utils#85]
I am not sure if the status number I am getting using the **getStatus()** method is a git status code or it is a **standard response** of this app? I have 3 files for testing, the **modified** file has **256** status number, the **deleted** file has **512** and **created** file has **128**. Someone enlighten me :) thanks!

**Comment by thomasjo** [comment]
Not well documented, but you can find the meaning behind the numbers here: https://github.com/atom/git-utils/blob/ad8c620d9e899136a85a2eadcde5bdad3cd9c67b/src/git.js#L5-L14
