### ISSUE TITLE
node-gyp rebuild --target=v12.3.1 

### ISSUE THREAD

**Issue by chatcan** [atom/git-utils#96]
result in 
`fatal error: too many errors emitted, stopping now [-ferror-limit=]`

while `node-gpy rebuild --target=v11.14.0` is ok

**Comment by robinpaulson** [comment]
I'm having problems with node v12.4.0:
"../src/repository.cc:717:46: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’"
"gyp ERR! stack Error: `make` failed with exit code: 2"
"gyp ERR! stack     at ChildProcess.onExit (/home/robin/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)"
"gyp ERR! stack     at ChildProcess.emit (events.js:200:13)"
"gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)"

**Comment by rsese** [comment]
Thanks for the report!  Would either of you like to send a pull request to fix this?  See this recent PR https://github.com/atom/node-nslog/pull/26 for example.
